@startmindmap
* Андрей Доличенко
** Контакты
*** Telegram: +7 913 566 8277
*** Email: anwerd@list.ru
*** LinkedIn/GitHub
** Должность
*** Ведущий системный аналитик
*** Архитектор решений
** Опыт работы
*** Bright Digital (2024-2025)
**** Проект для Газпромнефти
***** Архитектура системы
***** CI/CD внедрение
***** Управление командой
*** AmexDev (2023-2024)
**** Система для Самолет Плюс
**** Оптимизация БД
*** Luxoft (2020-2022)
**** Проекты для Сбера
**** Автоматизация BPMS
** Навыки
*** Методологии
**** BPMN/UML
**** TOGAF/C4
*** Технологии
**** Kafka/PostgreSQL
**** Kubernetes/Docker
** Образование
*** СибГАУ
**** Специалист (2006)
**** Бакалавр (2004)
** Достижения
*** 10+ enterprise-проектов
*** Оптимизация процессов
*** Внедрение стандартов
** Дополнительно
*** Языки
**** Русский (родной)
**** English (B2)
*** Готов к переезду
@endmindmap
