@startmindmap
skinparam monochrome false
skinparam style strictuml

*[#FF5733] Андрей Доличенко
**[#33A2FF] Контакты
***[#33FF57] Telegram: +7 913 566 8277
***[#33FF57] Email: anwerd@list.ru
***[#33FF57] LinkedIn/GitHub
**[#FF33A2] Должность
***[#FFBD33] Ведущий системный аналитик
***[#FFBD33] Архитектор решений
**[#A233FF] Опыт работы
***[#33FFBD] Bright Digital (2024-2025)
****[#FF5733] Проект для Газпромнефти
****_[#FF5733] Архитектура системы
****_[#FF5733] CI/CD внедрение
****_[#FF5733] Управление командой
***[#33FFBD] AmexDev (2023-2024)
****[#FF5733] Система для Самолет Плюс
****_[#FF5733] Оптимизация БД
***[#33FFBD] Luxoft (2020-2022)
****[#FF5733] Проекты для Сбера
****_[#FF5733] Автоматизация BPMS
**[#FF33A2] Навыки
***[#33A2FF] Методологии
****[#33FF57] BPMN/UML
****[#33FF57] TOGAF/C4
***[#33A2FF] Технологии
****[#33FF57] Kafka/PostgreSQL
****[#33FF57] Kubernetes/Docker
**[#A233FF] Образование
***[#33FFBD] СибГАУ
****[#FF5733] Специалист (2006)
****[#FF5733] Бакалавр (2004)
**[#FF33A2] Достижения
***[#33A2FF] 10+ enterprise-проектов
***[#33A2FF] Оптимизация процессов
***[#33A2FF] Внедрение стандартов
**[#A233FF] Дополнительно
***[#33FFBD] Языки
****[#FF5733] Русский (родной)
****[#FF5733] English (B2)
***[#33FFBD] Готов к переезду

' Сложные связи
@enduml
